x-veld:
  chain:

services:
  veld_create_config:
    extends:
      file: ./code/veld_code__train_spacy_ner/veld_create_config.yaml
      service: veld_create_config
    volumes:
      - ./data/configs/:/veld/output/
    environment:
      out_config_file: "config_test.cfg"
      lang: de
      ner: true
      optimize_efficiency: true
      pretraining: true

