x-veld:
  chain:
    description: "Creates a spacy training config according to passed arguments. See 
      https://spacy.io/usage/training/#config for the target outcome."
    topic:
      - "NLP"
      - "Machine Learning"

services:
  veld_create_config:
    extends:
      file: ./code/veld_code__spacy/veld_create_config.yaml
      service: veld_create_config
    volumes:
      - ./data/configs/:/veld/output/
    environment:
      out_config_file: "config_1.cfg"
      lang: de
      ner: true
      optimize_accuracy: true
      pretraining: true

