
services:
  misc:
    build: .
    volumes:
      - ../:/home/
    ports:
      - 8888:8888
    working_dir: /home/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password=''

