
services:
  veld_analysis:
    build: .
    volumes:
      - ./src/:/veld/code/
    ports:
      - 8888:8888
    working_dir: /veld/code/
    command: jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root

